### PR TITLE
[WIP] Feat codelab

### PR DESCRIPTION
**Pull request by zckrs**

### CODE REVIEW

**Comment by zckrs** [comment]
@Swiip @micaelmbagira should we really host the codelab or add a link to yeoman.io/codelab ?

**Comment by Swiip** [comment]
Don't know what's best, in one hand it's great to show that's it's the Yeoman reference, in the other hand we lose users from our own site / generator.

**Comment by zckrs** [comment]
> in the other hand we lose users from our own site / generator.

Not with target="_blank" xD

**Comment by Swiip** [comment]
Why not ;)

**Comment by zckrs** [comment]
Currently we have a link to Yeoman Codelab. At moment I close this PR.

**Pull request closed without merging**
